mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: per.neal.blog.entity
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crowblogdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: root
    password: neal
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 8
        max-wait: -1
    timeout: 50s
    # 默认已经配置了solr，如果无端口改动，就不需要改动
server:
  port: 8080
logging:
  level:
    root: info
    per.neal.blog.dao: debug